---
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-eap
    tags: eap,javaee,java,jboss
    version: 5.0.1-SNAPSHOT
    openshift.io/display-name: Entando Output Image Streams Template
    openshift.io/provider-display-name: Entando
    description: Entando Output Image Streams Template
    template.openshift.io/long-description: Entando Output Image Streams Template
    template.openshift.io/documentation-url: https://central.entando.com/
    template.openshift.io/support-url: https://central.entando.com
  name: entando-output-image-streams
labels:
  template: entando-eap71-postgresql-jenkins
message: 'Entando Output Image Streams Deployment were created'
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: entando-sample
  required: false
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      application: "${APPLICATION_NAME}"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}-appbuilder
    labels:
      application: "${APPLICATION_NAME}"
