---
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-wildfly
    tags: javaee,java,jboss
    version: 5.0.2
    openshift.io/display-name: Template to setup the Full Entando Stack App
    openshift.io/provider-display-name: Entando
    description: An template that facilitates the installation of the Full Entando Stack
    template.openshift.io/long-description: An template that facilitates the installation of the Full Entando Stack
    template.openshift.io/documentation-url: https://central.entando.com/
    template.openshift.io/support-url: https://central.entando.com
  name: entando-full-stack
labels:
  template: entando-demo
message: A new Entando Demo has been created in your project.
parameters:

- displayName: Domain suffix
  name: DOMAIN_SUFFIX
  description: Domain suffix will be appended to the various service names to form a full domain name for the Route of the
    mapped to the service. This parameter is required to ensure that the AppBuider points to the externally accessible
    URL that serves Entando Full Stack Engine App.
  value: ""
  required: true

- displayName: Image Stream Tag
  name: IMAGE_STREAM_TAG
  description: The Image Stream Tag to use for each of the Entando Images for which there is a DeploymentConfig. This
    Image Stream Tag should which generally corresponds with the Entando version to be used.
  value: 5.0.2
  required: false

- displayName: ImageStream Namespace
  name: IMAGE_STREAM_NAMESPACE
  description: Namespace in which the ImageStreams for Entando  images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  value: openshift
  required: true


- displayName: KIE Server base url
  name: KIE_SERVER_BASE_URL
  description: KIE Server base url
  value: 'http://entando-kieserver701.apps.serv.run/'
  required: false

- displayName: KIE Server Username
  name: KIE_SERVER_USERNAME
  description: KIE Server Username
  value: 'kieserver'
  required: false

- displayName: KIE Server Password
  name: KIE_SERVER_PASSWORD
  description: KIE Server Password
  value: 'kieserver1!'
  required: false

- displayName: Database Volume Capacity
  name: VOLUME_CAPACITY
  description: Size of persistent storage for database volume.
  value: 1Gi
  required: false


objects:
- kind: Service
  apiVersion: v1
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: "entando-full-stack-engine"
  metadata:
    name: "entando-full-stack-engine"
    labels:
      application: "entando-full-stack"
    annotations:
      description: The Entando Runtime server's http port.
- kind: Service
  apiVersion: v1
  spec:
    ports:
    - port: 5000
      targetPort: 5000
    selector:
      deploymentConfig: "appbuilder"
  metadata:
    name: "appbuilder"
    labels:
      application: "entando-full-stack"
    annotations:
      description: The Entando AppBuilder http port.
- kind: Route
  apiVersion: v1
  id: "entando-full-stack-engine-http"
  metadata:
    name: "entando-full-stack-engine-http"
    labels:
      application: "entando-full-stack"
    annotations:
      description: Route for the Entando Runtime's http service.
  spec:
    host: "entando-full-stack.${DOMAIN_SUFFIX}"
    to:
      name: "entando-full-stack-engine"
- kind: Route
  apiVersion: v1
  id: "entando-full-stack-appbuilder"
  metadata:
    name: "entando-full-stack-appbuilder"
    labels:
      application: "entando-full-stack"
    annotations:
      description: Route for application's http service.
  spec:
    host: "entando-full-stack-appbuilder.${DOMAIN_SUFFIX}"
    to:
      name: "appbuilder"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "entando-full-stack-engine"
    labels:
      application: "entando-full-stack"
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "entando-full-stack-engine"
        from:
          kind: ImageStreamTag
          name: "entando-sample-full:${IMAGE_STREAM_TAG}"
          namespace: "${IMAGE_STREAM_NAMESPACE}"
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentConfig: "entando-full-stack-engine"
    template:
      metadata:
        name: "entando-full-stack-engine"
        labels:
          deploymentConfig: "entando-full-stack-engine"
          application: "entando-full-stack"
      spec:
        terminationGracePeriodSeconds: 75
        containers:
        - name: "entando-full-stack-engine"
          image: "${IMAGE_STREAM_NAMESPACE}/entando-sample-full:${IMAGE_STREAM_TAG}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2Gi"
          livenessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - " /wildfly/bin/jboss-cli.sh --connect --commands=ls | grep 'server-state=running'"
            initialDelaySeconds: 60
          readinessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "/wildfly/bin/jboss-cli.sh --connect --commands='ls deployment' |
                grep war"
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          volumeMounts:
          - mountPath: "/entando-data"
            name: "entando-full-stack-pvol"
          env:
          - name: KIE_SERVER_BASE_URL
            value: "${KIE_SERVER_BASE_URL}"
          - name: KIE_SERVER_USERNAME
            value: "${KIE_SERVER_USERNAME}"
          - name: KIE_SERVER_PASSWORD
            value: "${KIE_SERVER_PASSWORD}"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumes:
        - name: "entando-full-stack-pvol"
          persistentVolumeClaim:
            claimName: "entando-full-stack-claim"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "entando-full-stack-appbuilder"
    generation: 1
    creationTimestamp:
    labels:
      application: "entando-full-stack"
    annotations: {}
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "entando-full-stack-appbuilder"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_STREAM_NAMESPACE}"
          name: appbuilder:${IMAGE_STREAM_TAG}
    replicas: 1
    selector:
      deploymentConfig: "entando-full-stack-appbuilder"
    template:
      metadata:
        creationTimestamp:
        labels:
          deploymentConfig: "entando-full-stack-appbuilder"
        annotations: {}
      spec:
        containers:
        - name: "entando-full-stack-appbuilder"
          image: "${IMAGE_STREAM_NAMESPACE}/appbuilder:${IMAGE_STREAM_TAG}"
          ports:
          - containerPort: 5000
            protocol: TCP
          env:
          - name: DOMAIN
            value: http://entando-full-stack.${DOMAIN_SUFFIX}/entando
          - name: CLIENT_SECRET
            value: appbuilder_secret
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "entando-full-stack-claim"
    labels:
      application: "entando-full-stack"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${VOLUME_CAPACITY}"
