---
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-eap
    tags: entando
    version: 5.0.3
    openshift.io/display-name: Template DB Secret for Entando applications
    openshift.io/provider-display-name: Entando
    description: "Template Secret for Entando applications."
    template.openshift.io/long-description: "Template Secret for Entando applications"
    template.openshift.io/documentation-url: "https://central.entando.com/"
    template.openshift.io/support-url: "https://central.entando.com"
  name: entando-secret
labels:
  template: entando-db-secret
message: 'A new DB Secret for Entando applications has been created'
parameters:
- displayName: Application Name
  description: The name for the Entando applcation. Used as a label as a convenience to allow for bulk operations
  name: APPLICATION_NAME
  required: true
- displayName: Secret Name
  description: The name for the secret.
  name: SECRET_NAME
  required: true
- displayName: Username
  description: The username of the user
  name: USERNAME
  value: dummy
  required: false
- displayName: Password
  description: The password of the user
  name: PASSWORD
  value: dummy
  required: false
- displayName: Sync to Jenkins
  description: Sync the secret to Jenkins
  name: SYNC_TO_JENKINS
  value: "false"
  required: false
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${SECRET_NAME}
    labels:
      application: "${APPLICATION_NAME}"
      credential.sync.jenkins.openshift.io: "${SYNC_TO_JENKINS}"
  stringData:
    username: ${USERNAME}
    password: ${PASSWORD}
