---
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-eap
    tags: eap,javaee,java,jboss
    version: 5.0.2
    openshift.io/display-name: Entando Template for Demos
    openshift.io/provider-display-name: Entando
    description: An template that facilitates the installation of one of the Entando demos
    template.openshift.io/long-description: An template that facilitates the installation of one of the Entando demos
    template.openshift.io/documentation-url: https://central.entando.com/
    template.openshift.io/support-url: https://central.entando.com
  name: entando-demo
labels:
  template: entando-demo
message: A new Entando Demo has been created in your project.
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: entando-fsi-credit-card-dispute
  required: false
- displayName: Entando Image Stream Tag
  description: The Image Stream Tag to use, which generally corresponds with the Entando version to be used
  name: IMAGE_STREAM_TAG
  value: 5.0.2
  required: false
- displayName: Custom http Route Hostname for the AppBuilder
  description: 'Custom http Route Hostname for the AppBuilder. Leave blank for default
    hostname, e.g.: <service-name>-<project>.<default-domain-suffix>'
  name: ENTANDO_APP_BUILDER_HOSTNAME_HTTP
  value: ''
  required: false
- displayName: Custom http Route Hostname for the Entando runtime and legacy screens
  description: 'Custom http Route Hostname for the Entando runtime and legacy screens.
    Leave blank for default hostname, e.g.: <service-name>-<project>.<default-domain-suffix>'
  name: ENTANDO_RUNTIME_HOSTNAME_HTTP
  value: ''
  required: true
- displayName: Context root of the Entando Runtime web app
  description: 'Context root of the Entando Runtime web app'
  name: ENTANDO_WEB_CONTEXT
  value: ''
  required: true
- displayName: KIE Server base url
  description: KIE Server base url
  name: KIE_SERVER_BASE_URL
  value: ''
  required: false
- displayName: KIE Server Username
  description: KIE Server Username
  name: KIE_SERVER_USERNAME
  value: ''
  required: false
- displayName: KIE Server Password
  description: KIE Server Password
  name: KIE_SERVER_PASSWORD
  value: ''
  required: false
- displayName: Database Volume Capacity
  description: Size of persistent storage for database volume.
  name: VOLUME_CAPACITY
  value: 1Gi
  required: false
- displayName: ImageStream Namespace
  description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  value: openshift
  required: true
- displayName: ImageStream Name
  description: The name of the image stream of the selected demo image
  name: IMAGE_STREAM
  value: openshift
  required: true
- description: Container memory limit
  name: MEMORY_LIMIT
  value: 2Gi
  required: false
objects:
- kind: Service
  apiVersion: v1
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: "${APPLICATION_NAME}-runtime"
  metadata:
    name: "${APPLICATION_NAME}-runtime"
    labels:
      application: "${APPLICATION_NAME}-runtime"
    annotations:
      description: The Entando Runtime server's http port.
- kind: Service
  apiVersion: v1
  spec:
    ports:
    - port: 5000
      targetPort: 5000
    selector:
      deploymentConfig: "${APPLICATION_NAME}-appbuilder"
  metadata:
    name: "${APPLICATION_NAME}-appbuilder"
    labels:
      application: "${APPLICATION_NAME}-appbuilder"
    annotations:
      description: The Entando AppBuilder http port.
- kind: Route
  apiVersion: v1
  id: "${APPLICATION_NAME}-runtime-http"
  metadata:
    name: "${APPLICATION_NAME}-runtime-http"
    labels:
      application: "${APPLICATION_NAME}"
    annotations:
      description: Route for the Entando Runtime's http service.
  spec:
    host: "${ENTANDO_RUNTIME_HOSTNAME_HTTP}"
    path: "/${ENTANDO_WEB_CONTEXT}"
    to:
      name: "${APPLICATION_NAME}-runtime"
- kind: Route
  apiVersion: v1
  id: "${APPLICATION_NAME}-appbuilder"
  metadata:
    name: "${APPLICATION_NAME}-appbuilder"
    labels:
      application: "${APPLICATION_NAME}-appbuilder"
    annotations:
      description: Route for application's http service.
  spec:
    host: "${ENTANDO_APP_BUILDER_HOSTNAME_HTTP}"
    to:
      name: "${APPLICATION_NAME}-appbuilder"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-runtime"
    labels:
      application: "${APPLICATION_NAME}"
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}-runtime"
        from:
          kind: ImageStreamTag
          name: "${IMAGE_STREAM}:${IMAGE_STREAM_TAG}"
          namespace: "${IMAGE_STREAM_NAMESPACE}"
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentConfig: "${APPLICATION_NAME}-runtime"
    template:
      metadata:
        name: "${APPLICATION_NAME}-runtime"
        labels:
          deploymentConfig: "${APPLICATION_NAME}-runtime"
          application: "${APPLICATION_NAME}"
      spec:
        terminationGracePeriodSeconds: 75
        containers:
        - name: "${APPLICATION_NAME}-runtime"
          image: "${IMAGE_STREAM_NAMESPACE}/${IMAGE_STREAM}:${IMAGE_STREAM_TAG}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
          livenessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "/opt/eap/bin/livenessProbe.sh"
            initialDelaySeconds: 60
          readinessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "/opt/eap/bin/readinessProbe.sh"
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          volumeMounts:
          - mountPath: "/entando-data"
            name: "${APPLICATION_NAME}-entando-pvol"
          env:
          - name: KIE_SERVER_BASE_URL
            value: "${KIE_SERVER_BASE_URL}"
          - name: KIE_SERVER_USERNAME
            value: "${KIE_SERVER_USERNAME}"
          - name: KIE_SERVER_PASSWORD
            value: "${KIE_SERVER_PASSWORD}"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumes:
        - name: "${APPLICATION_NAME}-entando-pvol"
          persistentVolumeClaim:
            claimName: "${APPLICATION_NAME}-entando-claim"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-appbuilder"
    generation: 1
    creationTimestamp:
    labels:
      application: "${APPLICATION_NAME}-appbuilder"
    annotations: {}
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}-appbuilder"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_STREAM_NAMESPACE}"
          name: appbuilder:${IMAGE_STREAM_TAG}
    replicas: 1
    selector:
      deploymentConfig: "${APPLICATION_NAME}-appbuilder"
    template:
      metadata:
        creationTimestamp:
        labels:
          deploymentConfig: "${APPLICATION_NAME}-appbuilder"
        annotations: {}
      spec:
        containers:
        - name: "${APPLICATION_NAME}-appbuilder"
          image: "${IMAGE_STREAM_NAMESPACE}/appbuilder:${IMAGE_STREAM_TAG}"
          ports:
          - containerPort: 5000
            protocol: TCP
          env:
          - name: DOMAIN
            value: http://${ENTANDO_RUNTIME_HOSTNAME_HTTP}/${ENTANDO_WEB_CONTEXT}
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${APPLICATION_NAME}-entando-claim"
    labels:
      application: "${APPLICATION_NAME}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${VOLUME_CAPACITY}"
