kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Examples that can be installed into your project to allow you to
      test the Red Hat Business Central templates. You should replace the contents
      with data that is more appropriate for your deployment.
  name: example-app-secret
labels:
  template: example-app-secret
parameters:
- displayName: Secret Name
  description: The name for the secret to create
  name: SECRET_NAME
  value: businesscentral-app-secret
  required: true
- displayName: Application Name
  description: The name of the Application under which the secret is created
  name: APPLICATION_NAME
  value: entando-sample
  required: true
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    annotations:
      description: Default secret file with name 'jgroups' and password 'mykeystorepassword'
    name: "${SECRET_NAME}"
    labels:
      application: "${APPLICATION_NAME}"
  type: Opaque
  data:
    jgroups.jceks: zs7OzgAAAAIAAAABAAAAAwAHamdyb3VwcwAAAWaAxkBZrO0ABXNyADNjb20uc3VuLmNyeXB0by5wcm92aWRlci5TZWFsZWRPYmplY3RGb3JLZXlQcm90ZWN0b3LNV8pZ5zC7UwIAAHhyABlqYXZheC5jcnlwdG8uU2VhbGVkT2JqZWN0PjY9psO3VHACAARbAA1lbmNvZGVkUGFyYW1zdAACW0JbABBlbmNyeXB0ZWRDb250ZW50cQB+AAJMAAlwYXJhbXNBbGd0ABJMamF2YS9sYW5nL1N0cmluZztMAAdzZWFsQWxncQB+AAN4cHVyAAJbQqzzF/gGCFTgAgAAeHAAAAARMA8ECFGxk+ZNJV1yAgMDDUB1cQB+AAUAAAEIWD9pbvWz3doVSJro4+NbK0nb7qFZcu/vfIUPXLapaahtbaVHE/mGlnBXHn1/CXxrVvw7g9rPCq00lRil5w+VxGaHvuMDKqFcD7pM6/mU8f90YlNb2zFkFWiSyXybvjPrRYG0J1Avp5ehjRrsz5akECM3sotkXnB1jhaqOvcPaa9e3GqN6l+cFl8mKUv123Hoe7LfhWwX2Y1HPn/gBKKcHm6NX76X+pc/5MWwYFxUuDBDWhXXhfMv5dsn5/NnjkuIw8UebO6V2j4YOEiVOOHV/ceHQrJir+O8+koUELuSj9Homgq+UKoiVMgtndjdgKes5ksMDkdWEHwyu37BcXqpa3lfmbRfe+zBdAAWUEJFV2l0aE1ENUFuZFRyaXBsZURFU3QAFlBCRVdpdGhNRDVBbmRUcmlwbGVERVMkTdQN6OAnIalavrskPfuOfosd4A==
