version: '3.7'
services:
  postgresql:
    image: entando/postgresql:5.0.3-SNAPSHOT
    volumes:
     - entando-pg-volume:/var/lib/pgsql/data
    networks:
      entando-network:
        ipv4_address: 10.10.0.2
  engine-api:
    image: entando/engine-api:5.0.3-SNAPSHOT
    volumes:
     - entando-volume:/entando-data
    environment:
      PORTDB_URL: jdbc:postgresql://postgresql:5432/portdb
      SERVDB_URL: jdbc:postgresql://postgresql:5432/servdb
      PORTDB_USERNAME: agile
      SERVDB_USERNAME: agile
      PORTDB_PASSWORD: agile
      SERVDB_PASSWORD: agile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      entando-network:
        ipv4_address: 10.10.0.3
  appbuilder:
    image: entando/appbuilder:5.0.3-SNAPSHOT
    environment:
      DOMAIN: http://engine-api:8080/entando
    networks:
      entando-network:
        ipv4_address: 10.10.0.4

networks:
  entando-network:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/8

volumes:
  entando-volume:
  entando-pg-volume:
