version: '2'
services:
  engine-api:
    image: entando/engine-api:${ENTANDO_IMAGE_VERSION}
    ports:
     - "8080:8080"
    volumes:
     - entando-volume:/entando-data
  appbuilder:
    image: entando/appbuilder:${ENTANDO_IMAGE_VERSION}
    ports:
     - "5000:5000"
    environment:
      DOMAIN: http://${DOCKER_HOST_ADDRESS}:8080/entando
      CLIENT_SECRET: appbuilder_secret
volumes:
  entando-volume:
