version: '3.6'
services:
  engine-api:
    image: entando/engine-api:5.0.3-SNAPSHOT
    volumes:
     - entando-volume:/entando-data
    networks:
      entando-network:
        ipv4_address: 10.9.0.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
  appbuilder:
    image: entando/appbuilder:5.0.3-SNAPSHOT
    environment:
      DOMAIN: http://engine-api:8080/entando
      CLIENT_SECRET: appbuilder_secret
    networks:
      entando-network:
        ipv4_address: 10.9.0.3

networks:
  entando-network:
    ipam:
      driver: default
      config:
        - subnet: 10.9.0.0/8

volumes:
  entando-volume:

