apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: pv-template
parameters:
- name: NAME
objects:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: null
    name: ${NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    capacity:
      storage: 1Gi
    hostPath:
      path: /home/ampie/openshift.local.clusterup/openshift.local.pv/${NAME}/
      type: ""
    persistentVolumeReclaimPolicy: Recycle
 
